export const StaticData = {

    locator_breadcrumb:"Store Locator",
    FindLocationtext:"Find a Location",
    Usemylocation:"Use my location",
    Search:"Search",
    Brandname:"MATALAN",
    miles:"miles",
    tempClosed:"Temporirly Closed",
    StoreDetailbtn:"View Store Detail",
    Storehighlight:"Store Highlights",
    Days:"Days",
    Hours:"Hours",
    Minutes:"Minutes",
    Seconds:"Seconds",
    getDirection:"Direction",
    AllRegion:"All Regions of",
    NearStoretext:"OTHER MATALAN'S STORES NEAR",
    AllLocationtext:"View All Location",
    PagenotFound:"404 - Page Not Found",
    cantfind_page:"We're really sorry, we can't find the page you're looking for",
    Youcouldtry:"You could try",
    Previuspage:"Going back to the previous page",
    homePage:"Going back to the homepage",
    StoreFinder:"Store Finder",
    FAQs:"FAQs",
    DownloadApp:"Download Our App",
    cookie:"cookies policy",
    Closed:"Closed",
    DayofWeek:"Day of the Week",
    Reopenmessage:"Message - The store is temporarily closed. It will reopen at",
    Address:"Address",
    Telephone:"Telephone",
    Holdiay:"Holdiday Hours",
    }